### ISSUE TITLE
Bug: DropdownButtonAccessoryDescriptor.onClick event has the wrong type

### ISSUE THREAD

**Issue by amiram** [InboxSDK/InboxSDK#1168]
**Describe the bug**
DropdownButtonAccessoryDescriptor.onClick should have an event that has a dropdown field. Currently it is of MouseEvent type.
https://inboxsdk.github.io/inboxsdk-docs/navmenu/#dropdownbuttonaccessorydescriptor

Are you using the remote loaded SDK or bundled from NPM? if NPM, which version?
npm 2.1.40

**Comment by aleemstreak** [comment]
We'll gladly look over any PRs!

**Comment by wegry** [comment]
Because this type doesn't have two disparate definitions like #1169 and #1164 did, a patch for this would be changing the [one definition](https://github.com/InboxSDK/InboxSDK/blob/d32e615a996147df4a8747ec575db1b3863684f8/src/platform-implementation-js/dom-driver/gmail/views/gmail-nav-item-view.ts#L46) of the type.

To check that a patch worked against your own project, you'd 

1. Run `yarn` and then `yarn gulp` in the SDK. If those succeed,
2. In your project, run `yarn link -r [path-to-your]/InboxSDK/packages/core` (pnpm and npm have similar commands)
3. Run `tsc` against your project.
