### ISSUE TITLE
Question: Denying load of */pageWorld.js. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.

### ISSUE THREAD

**Issue by praveen7557** [InboxSDK/InboxSDK#796]
Getting the error `Denying load of chrome-extension://ececkagaccnfmkopaiemklekhoimmgpn/pageWorld.js. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.` in console of gmail.

```
import * as InboxSDK from '@inboxsdk/core';

InboxSDK.load(2, 'sdk_extension_284828').then((sdk) => {
  console.log('here'); // it's not coming here.
  sdk.Toolbars.addToolbarButtonForApp(
    appToolbarButton({
      onClick: () => {
        /** The inboxSDK API doesn't have a way to remove the dropdown arrow */
        const inboxSDKTooltip = document.querySelector('.inboxsdk__appButton_tooltip');
        inboxSDKTooltip && (inboxSDKTooltip.style.display = 'none');
      },
    }),
  );
});
```

I'm using latest version `"@inboxsdk/core": "^0.2.20"`.

**Comment by vanhorickanthony** [comment]
I got the same error while trying to update our plugin to MV3: 
`Denying load of chrome-extension://kghnedaofkajiklpngpfmngilkdoblgi/pageWorld.js. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.`.

I've tried manually allowing any resource with
`    "web_accessible_resources": [
        {
            "resources": [
            ],
            "matches": ["<all_urls>"],
            "extension_ids": []
        }
    ],`
Also tried to give permission to the `pageWorld.js`-resource, which also didn't work.

I'm using the latest version `"@inboxsdk/core": "^0.2.20".`

@praveen7557 have you found a work-around or solution yourself in the mean time?

**Comment by praveen7557** [comment]
@vanhorickanthony I added `pageWorld.js` in the webpack output files, so that it will be available with all the build files

<img width="822" alt="Screenshot 2022-11-29 at 10 38 40 AM" src="https://user-images.githubusercontent.com/13882201/204443937-e084537e-634d-4cb0-9f88-f8cddc9bafa5.png">

**Comment by tinacious** [comment]
I am also getting this issue. Here's how I (somewhat) solved it. I say "somewhat" because the console is full of errors from the Inbox SDK but the compose view functionality is working so I suppose this is good enough.


### Copy pageWorld.js

Copy it from the package, e.g.:

```sh
cp node_modules/@inboxsdk/core/pageWorld.js your-extension-root/pageWorld.js
```


### Add pageWorld.js to web_accessible_resources

I have tried adding pageWorld to the `web_accessible_resources` as follows:

```json
    {
      "resources": [
        "pageWorld.js"
      ],
      "matches": [
        "https://mail.google.com/*"
      ]
    }
```

### Copy the contents of InboxSDK's background.js into your own

Copy the contents of `node_modules/@inboxsdk/core/pageWorld.js your-extension-root/background.js` into your own background file. The [manifest v3 migration guide](https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/#manifest) for service workers says you can only have one.


### Add scripting permission

It appears the background script uses this for v3 but it still appears to work without it. 🤷‍♀️ 


## Errors

I still get some errors but the compose view appears to be working.

Do you have any suggestions for preventing these errrors from occurring/logging? 

Thanks! 🙏 


### Error 1: Error logged: TypeError: Cannot set properties of undefined (setting '_headers')

I've created an issue for that here: https://github.com/InboxSDK/InboxSDK/issues/812


### Error 2: Error in injected script Error: waitFor timeout

```
log-error.ts:93   Error logged: Error: waitFor timeout
    at n (pageWorld.js:11:29822)
    at a (pageWorld.js:10:13753)
```

## Build info

- Parcel to bundle TypeScript
- other scripts for copying assets over from Inbox SDK

**Comment by RustamY** [comment]
https://github.com/InboxSDK/hello-world

You need to pay attention to _webpack.common.js_ configuration

`
entry: {
    ...
    pageWorld: '@inboxsdk/core/pageWorld.js',
    background: '@inboxsdk/core/background.js',
  },
  ...
  plugins: [
    new CopyPlugin({
      patterns: [
        { from: "static" },
      ],
    }),
  ],
`

The **manifest.json** file must be in the folder with the build at the same level
