### ISSUE TITLE
Question: Is it possible to load external application using frames?

### ISSUE THREAD

**Issue by gs-gkommasani** [InboxSDK/InboxSDK#830]
**Question(s)**
We want to load our application inside gmail using Inboxsdk with frames. Is it possible with V3?

**Comment by Macil** [comment]
In order to have a Chrome extension place an iframe into a page like Gmail that uses strict Content-Security-Policy rules and have content in the iframe not be affected by the page's CSP rules, the iframe must be a static html file within the extension. You can then put a remote iframe inside of that one if you want. We actively use this technique in the Streak extension. There's an example in https://gist.github.com/Macil/9f8b3c9f4e671d4e422bd34901ff882f and a previous discussion in https://groups.google.com/g/inboxsdk/c/_lbRkZmVpCA/m/6cE9K9YdCgAJ.
