### ISSUE TITLE
Custom inboxSdk styles negatively impact composeView buttons

### ISSUE THREAD

**Issue by stijndeschuymer** [InboxSDK/InboxSDK#835]
<img width="540" alt="Screenshot 2023-02-02 at 12 07 41" src="https://user-images.githubusercontent.com/4083920/216311470-46e325fb-4897-40cb-9f7e-9b96c5cd02d0.png">

The customStyles add more margin to the buttons and make the buttons overflow the composeView.
This is reproducible in gmail with the helloWorld app in this repo (and my custom chrome extensions) `"@inboxsdk/core": "0.2.27",`.

Would you accept a merge request with a config param to opt out of loading the styles?

**Comment by aleemstreak** [comment]
Looks like this only affects compose windows that open really small because the window is small. I think we need to change the styles to not add this extra margin when in this "small mode".

**Comment by wegry** [comment]
It looks like the class being added [here](https://github.com/InboxSDK/InboxSDK/blob/3bfd440d2b7447057c593828756f5d9d1f3ff62b/src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view/manage-button-grouping.ts#L172) is actually making buttons wider (instead of narrowing them) like the name of the function.

https://github.com/InboxSDK/InboxSDK/blob/3bfd440d2b7447057c593828756f5d9d1f3ff62b/src/platform-implementation-js/style/gmail.css#L474 could be the custom CSS causing the trouble.

**Comment by aleemstreak** [comment]
The SDK should leave intact whatever gmail's styles are. Sometimes gmail widens the spacing and sometimes it makes it narrow based on the size of the viewport when Gmail was first loaded. The SDK should take that into account

**Comment by wegry** [comment]
@aleemstreak do you have an example of the narrowing? I may just be missing something, but with a `window.innerWidth` of 2294px, the selector `.wG.J-Z-I` has a margin of `4px 12px 4px 0`. The margin is identical at a `window.innerWidth` of 684px.

Maybe the reasoning for https://github.com/InboxSDK/InboxSDK/blob/3bfd440d2b7447057c593828756f5d9d1f3ff62b/src/platform-implementation-js/style/gmail.css#L474 is lost at this point too? Or it had/has something to do with the "More tools" button added by the SDK?
