### ISSUE TITLE
modal close icon in modals looks blurry on retina screen

### ISSUE THREAD

**Issue by wegry** [InboxSDK/InboxSDK#903]
**Describe the bug**

`InboxSDK.Widgets.showModalView` uses a 1x icon `url('https://www.gstatic.com/images/icons/material/system/1x/close_black_24dp.png')`. [Link](https://www.gstatic.com/images/icons/material/system/1x/close_black_24dp.png). This is blurry on retina displays.

**To Reproduce**

1. Invoke `InboxSDK.Widgets.showModalView({ ... })` on retina display. 
2. Note the blurry close icon in the top right.
 
https://github.com/InboxSDK/InboxSDK/blob/c745dac1ac2c1b2c14a00f2980e20c59395815a6/examples/modal-example/content.js#L49

has a usage of the `showModalView` method.

**Expected behavior**

We should either

- find a newer gmail class with display density awareness for a close icon OR
- detect higher dpi screens and use a corresponding icon instead

**Screenshots**

<img width="84" alt="Screenshot 2023-05-04 at 09 58 24" src="https://user-images.githubusercontent.com/5156873/236229985-75a3ff88-97cb-4a5f-9a7e-08596cf13d01.png">

**Comment by 1TheMuffinMan** [comment]
It would be neat to use an SVG implementation and solve it for good, but on the other, would be nice to use a higher res gmail asset (if they have one) so that if they change the asset altogether and retain the same name there is potentially no maintenance required. Of course, the latter relies on a hypothetical best-case scenario.
