### ISSUE TITLE
Loading InboxSDK causes issues with compose view Icon-set.

### ISSUE THREAD

**Issue by glr0221** [InboxSDK/InboxSDK#931]
**Describe the bug**
Loading InboxSDK breaks the iconl-list for compose window.

**To Reproduce**

1. Please download/clone the [hello-world-inboxsdk](https://github.com/InboxSDK/hello-world) project. 
2. Once cloned, please comment all codes within the InboxSDK.load() call. (lines 4-15)
3. Build the updated code and sideload it to your Chrome browser.
4. Enable the Hello-World extension for Incognito browser.
5. Open an incognito window of Chrome.
6. Resize the Incognito Chrome's width to approximately half of the screen. (DO NOT USE THE FULL WIDTH OF SCREEN)
7. Open GMAIL in one of the tabs of the incognito-chrome.
8. Click on compose and wait for the compose window to popup.

**Expected behavior**
Compose windows shows and the icons are correctly shown a the bottom. Please see this uploaded image : 
https://imgur.com/a/U58aCur

**Screenshots**
With the inboxsdk library loaded, and the incognito-Chrome window is of the right size, the bottom icons will look a bit weird. Please see this image :  https://imgur.com/kwcxs5p

Notice that the delete/trash icon is now beyond the compose window and is already at the right hand bar for addons. 

**Add any other context about the problem here if anything**
Just some emphasis on the bug happening in incognito and when incognito-window is not in full screen.

Thanks

**Comment by wegry** [comment]
Using a 1512px wide screen and adding three compose view buttons with https://github.com/InboxSDK/InboxSDK/blob/3bfd440d2b7447057c593828756f5d9d1f3ff62b/examples/compose-tooltip-button/content.js#L8, I can't repro.

Narrower screen widths than that, though, it looks like https://github.com/InboxSDK/InboxSDK/blob/3bfd440d2b7447057c593828756f5d9d1f3ff62b/src/platform-implementation-js/style/gmail.css#L457 is the line causing icons to burst the parent container's banks.

It appears the issue happens when https://github.com/InboxSDK/InboxSDK/blob/3bfd440d2b7447057c593828756f5d9d1f3ff62b/src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view/manage-button-grouping.ts#L194 comes back as true. Related to #835. 

The interaction between overflow rule and width checks is less than ideal. Without the [CSS overflow override](https://github.com/InboxSDK/InboxSDK/blob/3bfd440d2b7447057c593828756f5d9d1f3ff62b/src/platform-implementation-js/style/gmail.css#L457), we end up with native compose toolbar buttons being hidden entirely and not added to the native gmail overflow menu.

# Aside about `window.innerHeight`

Without the SDK, Gmail's ComposeView Toolbar Button display seem to be affected by `window.innerHeight` in addition to `window.innerWidth`.

## ~900px tall

Note "Set up a time to meet" is present in the compose view button toolbar overflow menu.

<img width="1624" alt="Screenshot 2023-07-24 at 16 05 13" src="https://github.com/InboxSDK/InboxSDK/assets/5156873/6d41834a-d65c-49d0-9f35-a0d36edc955c">

## Shorter window at ~700px tall

Note "Set up a time to meet" is present in the compose view button toolbar overflow menu.

<img width="1624" alt="Screenshot 2023-07-24 at 16 03 29" src="https://github.com/InboxSDK/InboxSDK/assets/5156873/97136297-ae75-4e6e-a52a-42b0f6b0adbe">
