### ISSUE TITLE
MessageView.getSender() throws an error for hidden messages in thread

### ISSUE THREAD

**Issue by avzabr** [InboxSDK/InboxSDK#939]
**Describe the bug**

MessageView.getSender() throws an error for hidden messages in thread:
* `Failed to find element with selector: td.gF span[email]`

**To Reproduce**

1. Great email thread with 6 messages
2. Register thread button
3. Try to get list of senders on thread button click

```typescript
InboxSDK.load(2, "Hello World!").then((sdk) => {
  sdk.Toolbars.registerThreadButton({
    title: 'Start',
    positions: ['THREAD'],
    iconUrl: StartImage,
    hasDropdown: true,
    onClick(event) {
      const selectedThreadViews = event.selectedThreadViews;
      const messages: InboxSDK.MessageView[] = selectedThreadViews.reduce(
          (acc, view) => acc.concat(view.getMessageViewsAll()),
          [],
      );
      const senders: string[] = messages.map((message) => message.getSender().emailAddress);

     // ISSUE when there are hidden messages in tread: MessageView.getSender() fails: `Failed to find element with selector: td.gF span[email]`

      onClick({
        root: event.dropdown.el,
        emails: [...new Set(senders)],
        onClose: () => event.dropdown.close(),
      });
    },
  });
});


```

**Expected behavior**

* `MessageView.getSender()` should return `null` OR `undefined` if the sender email cannot be found in DOM instead of throwing exception

**Screenshots**

![image](https://github.com/InboxSDK/InboxSDK/assets/17640566/ac170d8b-7581-4918-a8e3-335fb691bb25)
![image](https://github.com/InboxSDK/InboxSDK/assets/17640566/c92a73af-8674-4584-bf31-49a480792800)

**Comment by aleemstreak** [comment]
Great find. Def open to PRs!

**Comment by mnj93** [comment]
@aleemstreak @wegry Can I pick this one?

**Comment by aleemstreak** [comment]
Go for it!

**Comment by wegry** [comment]
After speaking with @Macil about this yesterday, the reported behavior is by design.

@avzabr in the example above, `ThreadRowView.prototype.getMessageViewsAll` is used. If `MessageView.prototype.getSender` is called before checking is `MessageView.prototype.isLoaded`, the former method can throw for hidden `MessageView`s. I've added draft TSDoc to that effect in https://github.com/InboxSDK/InboxSDK/commit/93a09962d7f5bb1334fd67eb097d279a3962a99a#diff-228b58b94f92eb5d122ef23d4c59e053a68825cd50db99feafe8fbf2731defcaR551.

That `ThreadRowView.prototype.getMessageViewsAll` returns all `MessageViews` associated with a thread, even those that have not been 'loaded'. 'loaded' in this case means 'not hidden'. Using `ThreadRowView.prototype.getMessageViews` instead should do the trick in this case.
